musicPlayTime: 30
choseTime: 15

reward:
  vault:
    enabled: false
    correct: 10
    wrong: 5
  command:
    enabled: false
    correct:
      - "give %playerName% diamond 1"
    wrong:
      - "give %playerName% dirt 1"

languages:
  default: "en_us"
  languages:
    - en_us
    - de_de

# currently not implemented!
bungeecord:
  enable: false
  lobby: Lobby

database:
  enable: false
  host: "127.0.0.1"
  port: 3306
  database: "WhatsTheSongsName"
  username: "root"
  password: "iMsooo1SavePassword"
